// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9-4b24SHgC4HXeisqaeBzhxPNrfwNwXc',
    appId: '1:115999468004:web:a62dbb732fd7201c8b3ff1',
    messagingSenderId: '115999468004',
    projectId: 'groceryapp-73757',
    authDomain: 'groceryapp-73757.firebaseapp.com',
    storageBucket: 'groceryapp-73757.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFTDkE98TkB-PiLEHUKfFY5TSqrma4PYo',
    appId: '1:115999468004:android:f453b1f60dcc4d528b3ff1',
    messagingSenderId: '115999468004',
    projectId: 'groceryapp-73757',
    storageBucket: 'groceryapp-73757.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA9-4b24SHgC4HXeisqaeBzhxPNrfwNwXc',
    appId: '1:115999468004:web:14df6e9727953a158b3ff1',
    messagingSenderId: '115999468004',
    projectId: 'groceryapp-73757',
    authDomain: 'groceryapp-73757.firebaseapp.com',
    storageBucket: 'groceryapp-73757.firebasestorage.app',
  );
}
